### ISSUE TITLE
Terraform

### ISSUE THREAD

**Issue by moshloop** [flanksource/config-db#10]
Scrape terraform state files from S3 / GCS - create a Terraform config per statefile and link in created resources

```yaml
terraform:
  -  name:  "{{ .path | path.split | index 0}}"  # infer terraform config name from path or from the JSON content of the terraform sate
      state: 
       s3:
          path: bucket/**/*.tfstate

```
