### ISSUE TITLE
Slow syncing of ProgressDeadlineExceeded

### ISSUE THREAD

**Issue by adityathebe** [flanksource/config-db#1405]
ProgressDeadlineExceeded is not picked up by config-db. We need to wait for the full-scrape.

Initially

```yaml
status:
  replicas: 1
  conditions:
    - type: Available
      reason: MinimumReplicasUnavailable
      status: "False"
      message: Deployment does not have minimum availability.
    - type: Progressing
      reason: ReplicaSetUpdated
      status: "True"
      message: ReplicaSet "bad-image-deployment-657df9457" is progressing.
  updatedReplicas: 1
  unavailableReplicas: 1
```

Changed to (in few minutes)

```yaml
status:
  conditions:
  - lastTransitionTime: "2025-03-17T10:42:20Z"
    lastUpdateTime: "2025-03-17T10:42:20Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2025-03-17T10:52:21Z"
    lastUpdateTime: "2025-03-17T10:52:21Z"
    message: ReplicaSet "bad-image-deployment-657df9457" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
```

But config-db hasn't updated the manifest

![Image](https://github.com/user-attachments/assets/d7952df4-772f-437c-b606-fafb762e65ba)
