### ISSUE TITLE
Upgrade checker analysis

### ISSUE THREAD

**Issue by moshloop** [flanksource/config-db#147]
```
upgradeChecker:
   - type: helm
      resources:
          kubernetes:
               - kind: HelmChart
      repo: $.spec.repo
      version: $.spec.chart.version
   - type: ami
   - type: sns
```
