### ISSUE TITLE
Allow configs to return events and/or cost

### ISSUE THREAD

**Issue by moshloop** [flanksource/config-db#150]
i.e. 

```yaml
full: true
```

with return expected:

```yaml
config: ...
changes: ...
cost: ...
```
