### ISSUE TITLE
Cloud Trail - Use principalid over role arn

### ISSUE THREAD

**Issue by moshloop** [flanksource/config-db#1502]
Created by should be `john` not `Administrators`
```yaml
userIdentity:
  arn: arn:aws:sts::4324:assumed-role/Administrators/john
  type: AssumedRole
  accountId: "324"
  sessionContext:
    attributes:
      creationDate: 2025-05-16T15:59:19Z
      mfaAuthenticated: "true"
    sessionIssuer:
      arn: arn:aws:iam::21321:role/Administrators
      type: Role
      userName: Administrators
      accountId: "213213"
    webIdFederationData: {}
```
