### ISSUE TITLE
Better support for location hierarchy 

### ISSUE THREAD

**Issue by moshloop** [flanksource/config-db#1546]
@adityathebe @yashmehrotra - What do you think of adding a logical and network location path? e.g.

aws/eu-west-1/{account | project}/cluster/namespace/
aws/eu-west-1/{account | project}/vpc/eu-west-1a/subnet/{instance}

or named locations:

deploy://github/repo/cluster/namespace/{helmrelease | argo app}
namespace://aws/eu-west-1/{account | project}/cluster/namespace/
node://aws/eu-west-1/{account | project}/vpc/eu-west-1a/subnet/{instance}
helm://{cluster}/{namespace}/{name}
kustomization://{cluster}/{namespace}/{name}
zone://
subnet://
vpc://
git://git-repo/file

_Originally posted by @moshloop in https://github.com/flanksource/mission-control/pull/2139#discussion_r2149531119_

**Comment by moshloop** [comment]
```yaml

spec:

       - type: AWS::VPC
        # In config/children endpoint - for each location like alias, query {alias} in locations. for children at any level below.
          aliases:
             - network://{{tags.region}}/{{.vpcId}}
       - type: AWS::*
       # only resources that have all these tags 
       filter: all([tags.region, tags.zone, tags.vpc, tags.subnet])

#       (i.e.  parents in the right hand size details
       locations:
        - vpc://{{.tags.vp}}
        - network:{{tags.region}}/{{.tags.zone}}/{{.tags.vpc}}/{{tags.subnet}}
```
