### ISSUE TITLE
Config Views

### ISSUE THREAD

**Issue by moshloop** [flanksource/config-db#1555]
```
kind: View
name: Deployments
summary:
    - type: count
      groupBy: environment
      description: Count of deployments by environment.
    - type: average
      field: duration
      groupBy: environment
      description: Average deployment duration by environment.
columns:
  - name: repo
    type: string
    description: The repository name.
  - name: branch
    type: string
    description: The branch name.
  - name: environment
    type: string
    description: The environment where the deployment occurred.
  - name: status
    type: string
    description: The status of the deployment (e.g., success, failure).
  - name: timestamp
    type: datetime
    description: The timestamp of the deployment.
  - name: duration

    type: integer
    description: The duration of the deployment in seconds.
  - name: user
    type: string
    description: The user who initiated the deployment.

configs:
  - query: type=Github::Workflow changeType=Workflow*
    max: 1
    groupBy:
      - repo
      - environment
    mapping:
      repo: $.repository.name
      branch: head_branch
      environment: environment.name
      status: conclusion
      timestamp: created_at
      duration: run_duration
      user: actor.login
  - query: type=Flux::Kustomization, changeType=updated
    mapping:
      repo: $.metadata.name
      branch: $.spec.sourceRef.branch
      environment: $.spec.environment
      status: $.status.phase
      timestamp: $.metadata.creationTimestamp
      duration: $.status.duration
      user: $.spec.user
```
