### ISSUE TITLE
JSONPath Analyzer

### ISSUE THREAD

**Issue by moshloop** [flanksource/config-db#18]
```yaml
- name: MissingPatches
  type: EC2Instance
  jsonpath:
    - $.Patches[*] ? (@.State == "Missing")
  message:
    expr: map(filter(Patches, {.State == "Missing"}), {.Title})
```
