### ISSUE TITLE
[YAML/JSON] File Scraper

### ISSUE THREAD

**Issue by moshloop** [flanksource/config-db#19]
For each file found in the globbing pattern, convert it to JSON and extract the id and type

```yaml
- file:
       type: $.kind
       id: $.metadata.name
       path: 
          - config/*.yaml
          - config/*.json 
       
```
