### ISSUE TITLE
Extract created by from cloudwtach events

### ISSUE THREAD

**Issue by moshloop** [flanksource/config-db#216]
i.e. use userIdentity.userName to find a person, if not found put the name in external_created_by 
```yaml
userIdentity:
  arn: arn:aws:iam::745897381572:user/moshe@flanksource.com
  type: IAMUser
  userName: moshe@flanksource.com
```
