### ISSUE TITLE
JSONPath change type rules

### ISSUE THREAD

**Issue by moshloop** [flanksource/config-db#251]
Given a config of:

```json
{
  "kind": "HelmRelease",
  "spec": {
    "chart": {
      "spec": {
        "chart": "mysql",
        "version": "8.8.8",
        "sourceRef": {
          "kind": "HelmRepository",
          "name": "bitnami",
          "namespace": "flux-system"
        },
        "reconcileStrategy": "ChartVersion"
      }
    },
    "values": {
      "auth": {
        "database": "service_instance_db"
      },
      "primary": {
        "livenessProbe": {
          "enabled": "false"
        },
        "readinessProbe": {
          "enabled": "false"
        }
      }
    },
    "interval": "5m",
    "releaseName": "customers-db-mysql"
  },
  "status": {
    "failures": 274,
    "helmChart": "flux-system/prod-customers-db-mysql",
    "conditions": [
      {
        "type": "Ready",
        "reason": "ArtifactFailed",
        "status": "False",
        "message": "HelmChart 'flux-system/prod-customers-db-mysql' is not ready"
      }
    ],
    "observedGeneration": 1
  },
  "metadata": {
    "uid": "674bf0fa-d843-423c-9568-c852bd2118db",
    "name": "customers-db-mysql",
    "labels": {
      "app": "petclinic-cloud",
      "cluster": "azure-demo-cluster",
      "namespace": "prod",
      "environment": "prod"
    },
    "namespace": "prod",
    "finalizers": [
      "finalizers.fluxcd.io"
    ],
    "annotations": {},
    "creationTimestamp": "2023-06-05T07:48:47Z"
  },
  "apiVersion": "helm.toolkit.fluxcd.io/v2beta1"
}
```

and a change patch of 
```json
{
  "status": {
    "failures": 262
  }
}
```

with a change type rule of:

```yaml
-  filter:   change_type == 'diff' && config_type  == 'HelmRelease'  # GOCel filter which configs this rule applies to, looks at config only
    rule:  patches.status.failures > 0  #gocel evaluation of config/patch/
    type: HelmReconcileFailed # replace diff change type
    summary: "Reconcile failed {{.patches.status.failures}} times"
```
