### ISSUE TITLE
Config type views

### ISSUE THREAD

**Issue by moshloop** [flanksource/config-db#29]
Create a mechanism to define a schema for config types

- [ ] Database table: config_item_schema 
- [ ] A job that runs periodically to generate a postgres view for each config type, enabling queries like: 
 ```SELECT Account,Name,OS FROM EC2Instance```
```yaml
name: EC2Instance
description: EC2 Instances
columns:
   - name: Account
      path: $.vpc_id
   - name: Name: 
      path: $.tags.Name
   - name: OS
      path: $.Inventory.PlatformName
```

Which would generate SQL like:

```SQL
SELECT 
config:::json#>'{vpc_id}' As Account
config:::json#>'{tags,Name}' As Name
config:::json#>'{Inventory,PlatformName}' As OS
FROM config_item
WHERE config_type = 'EC2Instance'
```

From a column perspective the path field only supports a jsonpath with a normal path (no filtering, indexing etc is required)
