### ISSUE TITLE
Change retention rules

### ISSUE THREAD

**Issue by moshloop** [flanksource/config-db#307]
drop all ReconciliationSucceeded changes older than 1d or when there are more than 10
```
kind:  Scraper:
retention: 
   changes:
       - name: ReconciliationSucceeded
          age: 1d
          count: 10

```
