### ISSUE TITLE
Azure - strip etags off resources

### ISSUE THREAD

**Issue by moshloop** [flanksource/config-db#317]

**Comment by moshloop** [comment]
This includes in nested resources e.g.

```yaml
**etag: W/"96cc4008-3132-4d9d-931d-44edb3f0218d"**
id: /subscriptions/0cd017bb-aa54-4611-b21f-ecf8daee0511/resourceGroups/crossplane/providers/Microsoft.Network/virtualNetworks/crossplane-vnet
location: northeurope
name: crossplane-vnet
properties:
  subnets:
    - id: /subscriptions/0cd017bb-aa54-4611-b21f-ecf8daee0511/resourceGroups/crossplane/providers/Microsoft.Network/virtualNetworks/crossplane-vnet/subnets/default
      **etag: W/"96cc4008-3132-4d9d-931d-44edb3f0218d"**
```
