### ISSUE TITLE
Chart - Least Privileged RBAC

### ISSUE THREAD

**Issue by moshloop** [flanksource/config-db#339]
```yaml
rbac:
      # Whether to create cluster of namespaced scoped roles
      scope:  Cluster
     # for secret management with valueFrom
      tokenRequest: true
      secrets: true
      configmaps: true
      # for use with kubernetes resource lookups
      readAll: true
      # for kubernetesFile lookups
      exec: true
```
