### ISSUE TITLE
Transform properties

### ISSUE THREAD

**Issue by moshloop** [flanksource/config-db#348]
Provide a mechanism for adding properties to  objects after scrape: e.g.

```yaml
kubernetes:
  properties:
     "Kubernetes::Pod": 
       - name: Logs
          icon: opensearch
          url: https://opensearch.svc/_dashboards/app/discover#/?_a=(query:(language:kuery,query:'kubernetes_pod_id:{{.id}}'))
     "Kubernetes::Node":
       - name: Grafana
          icon: grafana
          url: https://grafana.svc/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?var-namespace={{.name}}      
```  

This will require adding a properties column of the same type used by components.
