### ISSUE TITLE
Add transform.relationships

### ISSUE THREAD

**Issue by moshloop** [flanksource/config-db#357]
Like Kubernetes relationships, but let a CEL expression return the Type, namespace, name tuples

```yaml
transform:
   relationships:
       - filter: type == 'Kubernetes::Application"
          expr:  [{name: 'a', namespace:'b', type: 'c']
```
