### ISSUE TITLE
SQL Scraper

### ISSUE THREAD

**Issue by moshloop** [flanksource/config-db#40]
Use https://github.com/xo/usql (either by calling an external binary or via library call) to implement a scraper:

The corresponding usql call would be:

```bash
 usql postgresql://postgres:postgres@localhost:5432 -c '    select t1.datname AS db_name,            pg_database_size(t1.datname) /1024/1024 as db_size_mb    from pg_database t1' -q -J
```

```yaml
usql:
   type: PostgresSQLDB
   id: $.db_name
   query: |+
    select t1.datname AS db_name,  
          pg_database_size(t1.datname) /1024/1024 as db_size_mb
    from pg_database t1
   url:  # use kommons.EnvVarValue
      value:  postgres://user:pass@localhost:5432/postgres
```

From these the output would be a config_item per database, with a body of:
```json
 {
    "db_name": "postgres",
    "db_size_mb": 8
  }
```
