### ISSUE TITLE
Change mapping

### ISSUE THREAD

**Issue by moshloop** [flanksource/config-db#417]
```
   
  changes:
      retention:
         - type: PodCrashLooping
            count: 10
            age: 72h
      
   transform:
        change:
            mapping:
               - filter: type == 'diff' && summary == "status.containerStatuses"  && patch.containerStatus.restartCount != null
                  type: PodCrashLooping
                  

```
