### ISSUE TITLE
K8S Connections - Native Cloud Providers 

### ISSUE THREAD

**Issue by moshloop** [flanksource/config-db#441]
i.e. specify

```
kubernetes:
  - kubeconfig:
         aws:
              cluster: 
                  value: 
              region: 
                  value: 
```
