### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by moshloop** [flanksource/config-db#463]
Tags are similar to labels, except that there are a max of 5, and in the ui they are normally shown without the label

```yaml
spec:
  kubernetes:
     - tags:
          - name: cluster
          - label:  alpha.eksctl.io/cluster-name
          - name: namespace
             jsonpath: metadata.namespace
          - name: division
             value: finance
```
e.g. 

podinfo-abc-123 `kube-system` `demo-cluster`
vm123 `eu-west-1` `prod-account` 

- Stored as a list of strings with an index, 
- Rename existing tags column to labels 
- Update resource selector and selected resource to include tags
- Remove account and namespace columns
