### ISSUE TITLE
Allow flexibility when forming labels

### ISSUE THREAD

**Issue by adityathebe** [flanksource/config-db#474]
example:

```yaml
spec:
  kubernetes:
    labels:
      - name: controller
        label: app/controller
      - name: replicas
        jsonpath: $.spec.replicas
```

or maybe a cel expression 

```yaml
spec:
  kubernetes:
    labels:
      - name: controller
        expr: spec.metadata.labels['app/controller']
      - name: replicas
        expr: spec.replicas 
```
