### ISSUE TITLE
Kubernetes

### ISSUE THREAD

**Issue by moshloop** [flanksource/config-db#6]
```
kubernetes:
   kubeconfig: ...
   resources:
     - v1/Pod
     - Deployment
     - ..
   include:
      - app=app1
   exclude:
      - app=cron
```
