### ISSUE TITLE
Custom Annotations 2.0

### ISSUE THREAD

**Issue by moshloop** [flanksource/config-db#654]
-  `config-db.flanksource.com/playbook-run-id`
-  `config-db.flanksource.com/deleted` override deleted date
-  `config-db.flanksource.com/mask: data.*` 
-  `config-db.flanksource.com/properties: `  JSON/YAML relationship  properties
-  `config-db.flanksource.com/exclude: status.managedFields` 
-  `config-db.flanksource.com/owner` add team owner
- `config-db.flanksource.com/relations` JSON/YAML relationship snippet
```yaml
annotations:
   config-db.flanksource.com/relations: |
             - type:
                    value: 'Kubernetes::Deployment'
                name: "$(.name)"
```
