### ISSUE TITLE
Azure pipelines

### ISSUE THREAD

**Issue by moshloop** [flanksource/config-db#66]
```yaml
azurePipelines:
  - project: flanksource/Demo1
```

Using https://learn.microsoft.com/en-us/rest/api/azure/devops/pipelines/pipelines/list?view=azure-devops-rest-6.0 query a specific Azure Devops project and return config items for each pipeline.

i.e. 
```yaml
organization: flanksource
project: Demo1
name: Pipeline
id: 1
folder: pipelines
url: 
```
