### ISSUE TITLE
Extract name for SNS/SQS

### ISSUE THREAD

**Issue by moshloop** [flanksource/config-db#706]
+ Use CreatedTimestamp

Unwrap the Attributes and Policy:

```
  Policy: 
   - Version: '2012-10-17'
      Id: sqspolicy
      Statement:
     - Sid: First
       Effect: Allow
       Principal: "*"
       Action: sqs:SendMessage
       Resource: arn:aws:sqs:eu-west-1:765618022540:demo-dev-queue
      Condition:
          ArnEquals:
               aws:SourceArn: arn:aws:sns:eu-west-1:765618022540:demo-dev-topic
  account: "765618022540"
  QueueArn: arn:aws:sqs:eu-west-1:765618022540:demo-dev-queue
  DelaySeconds: "90"
  CreatedTimestamp: "1719922363"
  VisibilityTimeout: "30"
  MaximumMessageSize: "2048"
  SqsManagedSseEnabled: "true"
  LastModifiedTimestamp: "1719922390"
  MessageRetentionPeriod: "86400"
  ApproximateNumberOfMessages: "0"
  ReceiveMessageWaitTimeSeconds: "10"
  ApproximateNumberOfMessagesDelayed: "0"
  ApproximateNumberOfMessagesNotVisible: "0"
```
