### ISSUE TITLE
Slack - Changes from messages

### ISSUE THREAD

**Issue by moshloop** [flanksource/config-db#769]
```yaml
slack:
  token: xxx
  channels:
    - alerts-*
  rules:
    - mapping:
        severity:
          expr: >
            ":large_red_circle:" in text ? "high" : ":large_orange_circle:" in text ? "med" : "info"
        type:
          expr: >
            regexp.Find(":\w+: \w: (.*)\n|:", text)
        created_at:
        summary:
          expr: text
      config:
        # sequential list of selectors to attach the change to
        - name:
            value: regexp.Find("http://(\w+)", text)
          type:
            value: MongoDB
          tags:
            a: b
        - type:
            value: AWS::Account
      filter:
        #  matchitems: * for any bot, or bot name
        bot: mongodb-atlas-alert-app
        user:
          name: '!*' # skip user message
          displayName:
        # CEL filter
        expr:
```
The mapping and filtering rules should be externalized so they can be used for generic HTTP / S3 / etc to change lookups
