### ISSUE TITLE
Field Masking

### ISSUE THREAD

**Issue by moshloop** [flanksource/config-db#78]
e.g. 

```yaml

kubernetes:
    - exclusions:
       - Secret
       - ReplicaSet
       - APIService
      transform:
        exclude:
           - jsonpath: $.metadata.uid
        mask:
           - selector:
                  type: Secret # the config_type to apply masking for
              jsonpath: $.stringData
              value: md5sum # replace the value with an md5sum of the value so that change detection will still work
           - jsonpath: $.data
              selector:
                  type: Secret # the config_type to apply masking for
              value: "***" - replace the value with 3 stars
             
```

The could be tested with the file scraper, so its not necessarily specific to kubernetes - that is just what a common use case would be.
