### ISSUE TITLE
Scraper Permissions

### ISSUE THREAD

**Issue by moshloop** [flanksource/config-db#791]
```yaml
kind: ScrapeConfig
spec:
    permissions:
         - action: playbook:run
            principal:
              team: # id or name
              user: # id or name
              owner: true
```

This requires implementation in:

- DB for row level security based on the scraper_ids a user has access to 
-  Postgrest / gorm to pass through roles/scraper_ids
