### ISSUE TITLE
Git

### ISSUE THREAD

**Issue by moshloop** [flanksource/config-db#8]
```
git:
    url: path.to.git
    analyzers
     - name: maven
        path: pom.xml
     - name: kubernetes
        path:  specs/**/.yaml
     - name: customization
        filter:
          - **/kustomization.yam.
```
