### ISSUE TITLE
Allow templating scraper spec with a loop var

### ISSUE THREAD

**Issue by adityathebe** [flanksource/config-db#811]
```yaml
spec:
  http:
    - forEach:
        - types:
          - Mongo::Project
      url: "https://cloud.mongo.com/project/{{.forEach.ID}}"
     
```
