### ISSUE TITLE
CRD Sync

### ISSUE THREAD

**Issue by moshloop** [flanksource/config-db#836]
When crdSync is true, and the type is MissionControl:Playbook,Canary,Connection,Notification create and update the corresponding object in the db. 

This will enable things like generating a playbook for helm charts in artifacthub, or for terraform modules. 

```yaml
file:
   - type: MissionControl::Playbook
      url: github.com/flanksource/canary-checker
      paths:
         - **/mission-control-playbook.yaml
crdSync: true
```
